# Numpy Arrays

##### O numpy é uma biblioteca que se parece com uma lista, só que ela retorna um array. 
##### Uma caracterestica do numpy é retornar apenas um tipo de variavel. 
##### Ex: Se criarmos um numpy com 4 tipos de variaveis diferentes, ele vai converter tudo para um tipo só, exemplos a seguir

In [2]:
import numpy as np  # Importando o numpy

In [3]:
np.arange(10)  # Criamos um array de 10 numeros, perceba que o retorno é array, e nao lista.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,10,2)  # Podemos usar os intervalor e escolher de onde começar igual em uma lista

array([1, 3, 5, 7, 9])

##### Podemos tambem converter uma lista em array numpy, como podemos ver a seguir

In [5]:
lista = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
np.array(lista)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Exemplo de como o array converte tudo para um tipo de variavel

In [9]:
lista_exemplo = [4.3, 'Jose', True, 5]

In [10]:
np.array(lista_exemplo)  # Como podemos ver, ele converteu tudo para string, no caso string do numpy

array(['4.3', 'Jose', 'True', '5'], dtype='<U32')

# Numpy Array (Operações Inteligentes)

##### Outra Caracteristica importante do numpy é que conseguimos fazer operações de maneira mais facil do que em uma lista

In [12]:
import numpy as np

In [13]:
lista2 = [1,2,3,4,5]

In [14]:
array = np.array(lista2)

In [17]:
lista2*2  # Note que quando multiplicamos a lista direito, ela nos retorna a multiplicação dos elementos e nao dos valores

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [18]:
array*2  # E no caso do array ele multiplica os elementos, o que facilita em alguns casos

array([ 2,  4,  6,  8, 10])

##### Podemos tambem alem das operações realizar arredondamentos

In [19]:
lista3 = [1.1, 2.2, 3.5, 5.9]

In [20]:
array2 = np.array(lista3)

In [21]:
np.ceil(array2)  # Arredonda para cima

array([2., 3., 4., 6.])

In [22]:
np.floor(array2)  # Arredonda para baixo 

array([1., 2., 3., 5.])

In [23]:
np.around(array2)  # Arredondamento comum | Podemos tambem escolher a quantidade de caso colocando um ',n' depois do array2

array([1., 2., 4., 6.])

# Numpy Array (Indexando e Cortando _'Slicing'_)

##### A Indexação e o slicing é igual em lista (para acessar um elemento)
##### Se tiver duvida ou nao lembrar é so ver as aulas especificas de python

In [1]:
import numpy as np

In [3]:
array = np.arange(0,11)

In [8]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
array[3]  # Como podemos ver a indexação é a mesma coisa de lista

3

In [9]:
array[0:5]  # E como podemos ver aqui o slicing tambem

array([0, 1, 2, 3, 4])

In [10]:
array[5:]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
array[-1]  # pega só o ultimo

10

# Numpy Array (Multiplas Dimensões)

In [14]:
import numpy as np

In [24]:
array = np.arange(1,13)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
array.shape  # O shape nos retorna quantas linhas tem no array. O array por padrao tem 1 coluna com varias linhas

(12,)

In [23]:
remodelado = array.reshape(6,2)  # Primeiro linhas e depois colunas
remodelado

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [25]:
remodelado = array.reshape(3,4)  # Primeiro linhas e depois colunas
remodelado

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

##### Tambem da pra fazer as operações inteligentes

In [26]:
remodelado*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

##### Tambem conseguimos criar de modo tridimensional

In [28]:
remodelado = array.reshape(3,2,2)
remodelado

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [32]:
remodelado[0][1][1]  # Repare que estamos acessando primeiro os 4 primeiros numeros, depois os 2 segundos e depois o segundo

4

In [33]:
remodelado.shape

(3, 2, 2)

# Numpy Array e Boolean

##### Só mostrando que dá pra fazer condicionais (todos) com numpy

In [34]:
import numpy as np

In [35]:
array = np.arange(11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
cond = array > 5

In [37]:
cond

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

# Numpy e Números Aleatórios

In [38]:
import numpy as pd

In [54]:
np.random.seed(123)  # Faz com que o numero aleatorio seja fixo, se nao toda vez que rodarmos o escopo de baixo ele gera um novo

In [55]:
array_random = np.random.randint(1, 101, 20)  # Vai do 1 a 101 e me retorta 20 numeros aleatorios entre eles
array_random

array([67, 93, 99, 18, 84, 58, 87, 98, 97, 48, 74, 33, 47, 97, 26, 84, 79,
       37, 97, 81])